### ISSUE TITLE
How to debug failed logins?

### ISSUE THREAD

**Issue by nikita2206** [doy/rbw#177]
Since a few days ago I'm failing to log in with my Bitwarden.com account. It coincides with me updating Homebrew packages on my machine.

The issue manifests when prompting me for a password, and every time I enter one it says that the password is incorrect, `rbw purge` and `rbw register` don't help either.

So I'm wondering how can I debug this? Is there a way to enable debug logging?

I'm running rbw 1.10.2

**Comment by AgenB** [comment]
I just started using this app and I'm also having trouble logging in. I don't know if it's some new issue or the fact that I'm using special characters including native language letters. When I input those, two stars appear in the password field.
I can use the official bitwarden cli without an issue.
Using version 1.10.0

**Comment by doy** [comment]
can you try again with version 1.11.1? i made a change that may help here.

**Comment by jorgeluiscarrillo** [comment]
Fixed on my end since 1.11.0

**Comment by Dioprz** [comment]
On my side too!

@doy Thanks a lot for the fix and the project, I was really missing be able to use bitwarden from the CLI.

**Comment by doy** [comment]
i'm going to close this out since it appears to be fixed, but let me know if anyone is still running into this.

in terms of debugging this yourself, it tends to not really be that easy because the bitwarden server gives very little information back when logins fail. generally i start by trying to run through the api requests by hand in curl, and if it's not immediately apparent, i then start comparing the api requests made by rbw with the ones made by the official clients (https://github.com/bitwarden/clients/tree/main) to see what differences there are.

**Comment by Mic92** [comment]
In my case I just had to use `rbw unlock` instead of `rbw login`, but this was on vaultwarden rather than bitwarden.
