### ISSUE TITLE
Unable to unlock

### ISSUE THREAD

**Issue by skoster** [doy/rbw#5]
I'm getting the following error when executing `rbw unlock`:
```
rbw unlock: failed to unlock database: unimplemented cipherstring type: 6
```
Looks like maybe it's some functionality that's not yet implemented? I'm willing to help debug if needed but I'm not familiar with rust so I will need some assistance.

**Comment by doy** [comment]
this is pretty much the same issue as #2 except it's one of your organizations that has a key using an older format (and it's hard for me to fix for similar reasons). unfortunately this is harder to work around, because you'd probably have to delete and recreate the organization to make this start working, which is a whole bunch of effort. as with #2 i'll see what i can do about finding an older client that's able to generate these formats so that i can test the behavior, but it might be a bit. sorry!

**Comment by dabeeeenster** [comment]
Im running my own self hosted server using https://github.com/dani-garcia/bitwarden_rs and getting a similar error: `rbw login: failed to log in to bitwarden instance: unimplemented cipherstring type: 0` when running `rbw login`. This is running the 1.15.0 release of bitwarden_rs. 

I'm not sure how accurate the bitwarden_rs api is at reflecting the official one, but this is the first time Ive had a client behave differently than when using the official API. Not sure if these issues are related tho?!

**Comment by dabeeeenster** [comment]
This works for me now in version 0.4.4 👍

**Comment by skoster** [comment]
Unfortunately I'm still seeing the error. But I'm using the online version of Bitwarden rather than self-hosted.

**Comment by doy** [comment]
yeah, i didn't change anything related to this - more likely is that you deleted or changed an old password entry, which caused that entry to stop using the old format.

**Comment by iamkroot** [comment]
> getting a similar error: `rbw login: failed to log in to bitwarden instance: unimplemented cipherstring type: 0` when running `rbw login`.

I was able to fix this by resetting my master password from the settings (ensuring the "Rotate encryption keys" option is checked).
